# Tensor
Tensors are the building blocks in PyTorch.

A tensor is a N-dimensional matrix.:
* A scalar is a 0-dimensioanl tensor
* A vector is a 1-dimensional or first order tensor
* A matrix is a 2-dimensional or second order tensor.

A Tensor is a generalization of vectors and matrices to higher dimensions.

Many operations that we use to perform on scalars, vectors, and matrices can be performed on tensors.

# What exactly is Tensor??

If tensors are just a generalization of matrices to higher dimensions, why not just call it "multi-dimensional arrays"? 

The answer is "PyTorch Tensor can run on either CPU or GPU". Thus Tensors are not just multi-dimensional arrays, they can also run on a GPU.


# NumPy vs PyTorch Tensors



In [15]:
import numpy as np
import torch

In [16]:
# initializing 1D array and 1D Tensor

a = np.array([1, 2, 3])
print(f'NumPy Array: {a}')

b = torch.tensor([1, 2, 3])
print(f'PyTorch Tensor: {b}')

NumPy Array: [1 2 3]
PyTorch Tensor: tensor([1, 2, 3])


In [17]:
# initializing 2D arrays and 2D tensors

c = np.array([[1, 2, 3],
              [4, 5, 6]])
print(f'NumPy Array:\n{c}')

d = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])
print(f'\nPyTorch Tensor:\n{d}')


NumPy Array:
[[1 2 3]
 [4 5 6]]

PyTorch Tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])


We can see somewhat similar syntax. Lets check performance.

To compare the performance between NumPy arrays and PyTorch tensors on matrix multiplication we randomly initialize arrays/tensors and multiply them.

In [18]:
# 4D arrays
array1 = np.random.rand(100, 100, 100, 100)
array2 = np.random.rand(100, 100, 100, 100)

In [19]:
%%timeit
np.matmul(array1, array2)

1.3 s ± 60.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [20]:
# Transferring tensor to GPU

device = torch.device("cuda")

tensor1 = torch.rand(100, 100, 100, 100).to(device)
tensor2 = torch.rand(100, 100, 100, 100).to(device)

In [21]:
%%timeit
torch.matmul(tensor1, tensor2)

21.7 ms ± 69.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


We can clearly see that PyTorch Tensors outperformed NumPy arrays.

# Creating Tensors

We can start coding from the basics. 

A **scalar** contains a single value. We can say it is a 0-dimensional tensor.

In [22]:
# Scalar
scalar = torch.tensor(5)
print(scalar)

# check dimension
print(f'scalar dimension: {scalar.ndim}')

tensor(5)
scalar dimension: 0


This means that scalar is a single number and it is of type `torch.Tensor`.



A **Vector** is 1-dimensional tensor

In [23]:
# Vector
vector = torch.tensor([5, 5, 5])
print(vector)

# check dimension
print(f'Vector dimension: {vector.ndim}')

tensor([5, 5, 5])
Vector dimension: 1


A **Matrix** is a 2-dimensional tensor

In [24]:
Matrix = torch.tensor([[1, 2], 
                       [3, 4]])
print(Matrix)

# check dimension
print(f'Matrix dimension: {Matrix.ndim}')

tensor([[1, 2],
        [3, 4]])
Matrix dimension: 2


A **Tensor** is a generalization of vectors and matrices to higher dimensions.

Lets create Tensor

In [25]:
Tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
print(Tensor)

# check dimension
print(f'Tensor dimension: {Tensor.ndim}')

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
Tensor dimension: 3


In [26]:
# Check shape of Tensor
Tensor.shape

torch.Size([1, 3, 3])

## Random Tensors

It's rare to create Tensors by hand in deep learning. Instead, in a deep learning model we usually initialize random tensors.


In [27]:
# Create a random tensor of size (2, 3)
random_tensor = torch.rand(size=(2, 3))
random_tensor, random_tensor.dtype

(tensor([[0.8499, 0.6835, 0.1631],
         [0.0732, 0.7884, 0.1926]]),
 torch.float32)

Every time you run the above code, you get different random values.

It is a common practice to initialze tensors (such as a model's learning weights) with random values. But there are times, especially in research settings - where you want some assurance of the reproducibility of your results. By manually setting your random number generator’s seed you can achieve this.

`torch.manual_seed(seed)`, set the seed of the random number generator to a fixed value, so that when you call the function, the results will be reproducible.


In [28]:
torch.manual_seed(123)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(123)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665]])
tensor([[0.1366, 0.1025, 0.1841],
        [0.7264, 0.3153, 0.6871]])
tensor([[0.2961, 0.5166, 0.2517],
        [0.6886, 0.0740, 0.8665]])
tensor([[0.1366, 0.1025, 0.1841],
        [0.7264, 0.3153, 0.6871]])


we can see that random1 and random3 generated same values.

## Zeros and ones

Fillings tensors with zeros or ones.

In [29]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(2, 3))
zeros

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),)

In [30]:
# Create a tensor of all ones
ones = torch.ones(size=(2, 3))
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

# Tensor information

* `.shape` - shape of the tensor? (often, operations performed on two or more tensors require same shape)
* `.dtype` - datatype of the tensor stored
* `.device `- device the tensor stored on? (usually GPU or CPU)

In [31]:
# Create a random tensor
tensor_1 = torch.rand(3, 4)

print(tensor_1)
print(f"Shape of tensor: {tensor_1.shape}")
print(f"Datatype of tensor: {tensor_1.dtype}")
print(f"Device tensor is stored on: {tensor_1.device}") # will default to CPU

tensor([[0.0756, 0.1966, 0.3164, 0.4017],
        [0.1186, 0.8274, 0.3821, 0.6605],
        [0.8536, 0.5932, 0.6367, 0.9826]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Tensor operations

PyTorch operations are very similar to those of NumPy. We can work with both scalars and other tensors.

## Basic arithmetic

In [34]:
# Create a tensor  
tensor = torch.tensor([10, 20, 30, 40])
print(tensor)

# 
# addition
tensor_add = tensor + 10
print(tensor_add)

# substraction
tensor_sub = tensor - 10
print(tensor_sub)

# multiplication
tensor_mul = tensor * 10
print(tensor_mul)

# division
tensor_div = tensor/ 10
print(tensor_div)

tensor([10, 20, 30, 40])
tensor([20, 30, 40, 50])
tensor([ 0, 10, 20, 30])
tensor([100, 200, 300, 400])
tensor([1., 2., 3., 4.])


We can apply the same operations between different tensors of compatible sizes.

In [52]:
# Create a 4x3 tensor of 10s
tensor_1 = torch.ones((3,3)) * 10
print(f'tensor_1: \n {tensor_1}')

# Create a 3x2 tensor of 2s
tensor_2 = torch.ones((3,3)) * 2
print(f'tensor_2: \n{tensor_2}')

tensor_1: 
 tensor([[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]])
tensor_2: 
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [53]:
tensor_1 + tensor_2

tensor([[12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.]])

In [54]:
tensor_1 - tensor_2

tensor([[8., 8., 8.],
        [8., 8., 8.],
        [8., 8., 8.]])

In [55]:
tensor_1 / tensor_2

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])

In [56]:
tensor_1 * tensor_2

tensor([[20., 20., 20.],
        [20., 20., 20.],
        [20., 20., 20.]])

## Matrix multilpication

Matrix multiplication is a common operation in machine learning and deep learning. It can be implemented by `torch.matmul` method

`torch.matmul(input, other, *, out=None)` → Tensor
here parameters:

input (Tensor) – the first tensor to be multiplied

other (Tensor) – the second tensor to be multiplied

Keyword Arguments:
out (Tensor, optional) – the output tensor.




In [57]:
tensor_1 = torch.Tensor([1, 2, 3])
tensor_2 = torch.Tensor([4, 5, 6])

torch.matmul(tensor_1, tensor_1)

tensor(32.)

## min, max, mean, sum

In [62]:
# Create a tensor
a = torch.arange(0, 50, 5)
a

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [67]:
print(f"Minimum: {a.min()}")
print(f"Maximum: {a.max()}")
print(f"Mean: {a.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {a.sum()}")

Minimum: 0
Maximum: 45
Mean: 22.5
Sum: 225


The above can also be done using `torch` methods

In [69]:
torch.max(a), torch.min(a), torch.mean(a.type(torch.float32)), torch.sum(a)

(tensor(45), tensor(0), tensor(22.5000), tensor(225))

In [73]:
# Returns index of max and min values
print(f"The max value is at {a.argmax()}th position")
print(f"The min value is at {a.argmin()}th position")

The max value is at 9th position
The min value is at 0th position


## Change tensor datatype

You can change the datatypes of tensors using `torch.Tensor.type(dtype=None)`

dtype - the datatype you'd like to use.

In [82]:
# Create a tensor and check its datatype
tensor_1 = torch.arange(1, 20, 2)
print(tensor_a)
tensor_1.dtype

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])


torch.int64

In [83]:
# change dataype to float16
tensor_float16 = tensor_1.type(torch.float16)
tensor_float16

tensor([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.], dtype=torch.float16)

## Reshaping


In [101]:
# Create a tensor

a = torch.arange(1., 10.)
a, a.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

`torch.reshape()`: Returns a tensor with the same data and number of elements as input, but with the specified shape. When possible, the returned tensor will be a view of input. 

In [102]:
b = torch.reshape(a, (3, 3))
b, b.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

`torch.view`: The returned tensor shares the same data and must have the same number of elements, but may have a different size. For a tensor to be viewed, the new view size must be compatible with its original size and stride

both `torch.view` and `torch.reshape` are used to reshape tensors. If you just want to reshape tensors, use `torch.reshape`. If you're also concerned about memory usage and want to ensure that the two tensors share the same data, use `torch.view`. 
more details: https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch/54507446#54507446

In [103]:
c = a.view(3, 3)
c, c.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

# Stacking

`torch.stack()`: Concatenates a sequence of tensors along a new dimension. All tensors need to be of the same size.

In [116]:
# create a tensor
a = torch.arange(1., 5.)
print(f'original tensor: \n{a}')

# Stack tensors on top of each other
a_stacked = torch.stack([a, a, a, a], dim=0) 
print(f'stacked tensor: \n{a_stacked}')

original tensor: 
tensor([1., 2., 3., 4.])
stacked tensor: 
tensor([[1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.],
        [1., 2., 3., 4.]])


## Squeezing

`torch.squeeze()`: Returns a tensor with all specified dimensions of input of size 1 removed. (i.e., removing all single dimensions from a tensor)



In [119]:
# create a tensor
a = torch.zeros(2,1,3,1)
print(f'original tensor: \n{a}')
print(f"original shape: {a.shape}\n")

# squeezing
a_squeezed = a.squeeze()
print(f"Squeezed tensor: \n{a_squeezed}")
print(f"Squeezed shape: {a_squeezed.shape}")

original tensor: 
tensor([[[[0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.]]]])
original shape: torch.Size([2, 1, 3, 1])

Squeezed tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
Squeezed shape: torch.Size([2, 3])


To reverse of `torch.squeeze()` you can use `torch.unsqueeze()` to add a dimension value of 1 at a specific index.

In [123]:
print(f"Squeezed tensor: {a_squeezed}")
print(f"Squeezed shape: {a_squeezed.shape}\n")

## Add an extra dimension with unsqueeze
a_unsqueezed = a_squeezed.unsqueeze(dim=1)
print(f"UnSqueezed tensor: \n{a_unsqueezed}")
print(f"UnSqueezed shape: {a_unsqueezed.shape}")

Squeezed tensor: tensor([[0., 0., 0.],
        [0., 0., 0.]])
Squeezed shape: torch.Size([2, 3])

UnSqueezed tensor: 
tensor([[[0., 0., 0.]],

        [[0., 0., 0.]]])
UnSqueezed shape: torch.Size([2, 1, 3])


# Permute

`torch.permute(input, dims)`: Returns a view of the original tensor input with its dimensions permuted.

In [126]:
a = torch.randn(2, 3, 5)
print(f'Original tensor {a.size()}')

b = torch.permute(a, (2, 0, 1)).size()
print(f'Permuted tensor {b}')

Original tensor torch.Size([2, 3, 5])
Permuted tensor torch.Size([5, 2, 3])


# PyTorch tensors and NumPy

PyTorch has functionality to interact with NumPy.

`torch.from_numpy(ndarray)` - NumPy array -> PyTorch tensor (Creates a Tensor from a numpy.ndarray)

`torch.Tensor.numpy()` - PyTorch tensor -> NumPy array (Returns the tensor as a NumPy ndarray)

In [133]:
# NumPy array to Tensor
a1 = np.array([1, 2, 3])
t1 = torch.from_numpy(a)
t1

tensor([1, 2, 3], dtype=torch.int32)

In [137]:
# Tensor to Numpy array

t2 = torch.tensor([4, 5, 6])
a2 = torch.Tensor.numpy(t2)
a2

array([4, 5, 6], dtype=int64)